#!/bin/bash

working_dir=$(pwd)

if [ $(uname -s) = 'Darwin' ]
then
  PACKAGE_MGR='brew'
else
  PACKAGE_MGR='sudo apt-get'
fi

rsync --exclude ".git/" --exclude ".DS_Store" --exclude "setup" --exclude "vm" \
  -av --no-perms -q "$(dirname $0)/" ~

echo "\033[0;34mInstalling dependencies...\033[0m"

command -v git >> /dev/null 2>&1 || $PACKAGE_MGR install git
command -v zsh >> /dev/null 2>&1 || $PACKAGE_MGR install zsh && chsh -s $(which zsh)
command -v vim >> /dev/null 2>&1 || $PACKAGE_MGR install vim

echo "\033[0;34mSetting up zprezto...\033[0m"

if [ -d $HOME/.zprezto ]
then
  cd $HOME/.zprezto && git pull -q && cd $working_dir
else
  git clone --recursive https://github.com/sorin-ionescu/prezto.git $HOME/.zprezto
fi

echo "\033[0;34mSetting up Vundle...\033[0m"

if [ -d $HOME/.vim/bundle/Vundle.vim ]
then
  cd $HOME/.vim/bundle/Vundle.vim && git pull -q && cd $working_dir
else
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

vim +PluginInstall +qall

echo "\033[0;34mSetting up z...\033[0m"

mkdir -p $HOME/.shadowboxes $HOME/bin $HOME/man

if [ -d $HOME/.shadowboxes/z ]
then
  cd $HOME/.shadowboxes/z && git pull -q && cd $working_dir
else
  git clone https://github.com/rupa/z.git $HOME/.shadowboxes/z
  cd $HOME/bin && ln -s $HOME/.shadowboxes/z/z.sh z.sh
  cd $HOME/man && ln -s $HOME/.shadowboxes/z/z.1 z.1
  touch $HOME/.z
  source $HOME/bin/z.sh
fi

echo "\033[0;34mSetting up nvm...\033[0m"

if [ -d $HOME/.shadowboxes/nvm ]
then
  cd $HOME/.shadowboxes/nvm && git pull -q && cd $working_dir
else
  git clone https://github.com/creationix/nvm.git $HOME/.shadowboxes/nvm
  cd $HOME/bin && ln -s $HOME/.shadowboxes/nvm/nvm.sh nvm.sh
  source $HOME/bin/nvm.sh
fi
