#!/bin/sh

working_dir=$(pwd)

if [ $(uname -s) = 'Darwin' ]
then
  PACKAGE_MGR='brew'
else
  PACKAGE_MGR='apt-get'
fi

echo "\033[0;34mSetting up zprezto...\033[0m"

if [ -d '.zprezto' ]
then
  cd .zprezto && git pull -q && cd $working_dir
else
  git clone --recursive https://github.com/sorin-ionescu/prezto.git .zprezto
fi

if [ -d '~/.vim/bundle/Vundle.vim' ]
then
  cd .vundle && git pull -q && cd $working_dir
else
  git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

rsync --exclude ".git/" --exclude ".DS_Store" --exclude "setup" --exclude "vm" \
-av --no-perms -q . ~

vim +PluginInstall +qall

chsh -s $(which zsh)
