#!/bin/sh

WORKING_DIR=$(pwd)
[ $(uname -s) = 'Darwin' ] && IS_MAC=1 || IS_MAC=0

if [ $IS_MAC = 1 ]
then
  PACKAGE_MGR='brew'
else
  PACKAGE_MGR='sudo apt-get'
fi

rsync --exclude ".git/" \
      --exclude ".DS_Store" \
      --exclude "README.md" \
      --exclude "setup" \
      --exclude "vm" \
      -av --no-perms -q "$(dirname $0)/" ~

echo "\033[0;34mInstalling dependencies...\033[0m"

command -v make >> /dev/null 2>&1 || $PACKAGE_MGR install make
command -v git >> /dev/null 2>&1 || $PACKAGE_MGR install git
command -v curl >> /dev/null 2>&1 || $PACKAGE_MGR install curl
command -v zsh >> /dev/null 2>&1 || $PACKAGE_MGR install zsh && chsh -s $(which zsh)
command -v vim >> /dev/null 2>&1 || $PACKAGE_MGR install vim

echo "\033[0;34mSetting up Vundle...\033[0m"

if [ -d $HOME/.vim/bundle/Vundle.vim ]
then
  (cd $HOME/.vim/bundle/Vundle.vim; git pull -q)
else
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

cd $HOME; vim +PluginInstall +qall

echo "\033[0;34mSetting up z...\033[0m"

mkdir -p $HOME/.shadowboxes $HOME/bin $HOME/man

if [ -d $HOME/.shadowboxes/z ]
then
  (cd $HOME/.shadowboxes/z; git pull -q)
else
  git clone https://github.com/rupa/z.git $HOME/.shadowboxes/z
  (cd $HOME/bin; ln -s $HOME/.shadowboxes/z/z.sh z.sh)
  (cd $HOME/man; ln -s $HOME/.shadowboxes/z/z.1 z.1)
  touch $HOME/.z
  source $HOME/bin/z.sh
fi

echo "\033[0;34mSetting up n...\033[0m"

if [ -d $HOME/.shadowboxes/n ]
then
  (cd $HOME/.shadowboxes/n; git pull -q)
else
  git clone https://github.com/tj/n.git $HOME/.shadowboxes/n
  (cd $HOME/.shadowboxes/n; PREFIX=$HOME make install)
fi

if [ $IS_MAC = 1 ]
then
  cp fonts/*.otf /Library/Fonts/
fi
