Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/trusty64"
  config.vm.network "private_network", ip: (ENV["PRIVATE_NETWORK"] || "192.168.50.6")
  config.vm.synced_folder "..", "/shadowboxer", type: 'nfs', mount_options: ['nolock,vers=3,udp']
  config.ssh.forward_agent = true
end
